name: 릴리즈 수동 빌드 with TEST 1
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: 빌드
    runs-on: ubuntu-latest
    steps:
      - name: 소스 체크아웃
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 브랜치 이름 추출
        shell: bash
        run: |
          echo "SOURCE_TAG=$(echo ${{github.ref_name}})" >> $GITHUB_ENV
          echo "TAG=$( ${{github.ref_name}})" >> $GITHUB_ENV
